### ISSUE TITLE
How to update already existing queries?

### ISSUE THREAD

**Issue by thecoldstone** [cap-js-community/tree-sitter-cds#25]
I have run into the issue that queries for highlight and locals were modified in [previous commit](https://github.com/cap-js-community/tree-sitter-cds/commit/90046623ca11a14ffe64b1711727e2766ecffb1a). 
 
 `:checkhealth` was showing some issues related to wrong structure within files _highlights_ and _locals_.
 
![Screenshot 2024-02-07 at 11 47 10](https://github.com/cap-js-community/tree-sitter-cds/assets/44757028/a6245988-45fa-4eff-9b9f-b8c1dea5109a)

 **Question**:
 Are queries updated along with other components of nvim-treesitter-cds by running `:TSUpdate cds`?
  
 **Solution**:
 Manually change queries according the latest updates in 
 `.local/share/nvim/lazy/nvim-treesitter/queries/cds`

**Comment by bugwelle** [comment]
Found their statement: https://github.com/nvim-treesitter/nvim-treesitter/discussions/5608#discussioncomment-7450342

**Comment by bugwelle** [comment]
The script uses `nvim --headless -c 'echo stdpath("config")' -c 'q'` to get NeoVim's config/runtime directory. Queries must be written there, see https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-queries

> Queries are what nvim-treesitter uses to extract information from the syntax tree; they are located in the `queries/{language}/*` runtime directories (see `:h rtp`), 

I didn't look to much into lazy (I didn't use it at first). Do they have custom queries directories that work as well? Would be great to know!
You can set the environment variable `NVIM_CONFIG_DIR="$HOME/.local/share/nvim/lazy/nvim-treesitter"` if you want the script to copy the files there. 😄

**Comment by bugwelle** [comment]
A bit of documentation was added via #26. Open for further ideas and remarks (especially in regard to `lazy`). 😄

**Comment by bugwelle** [comment]
I'm closing this issue. With #27 I've added another sentence to our documentation. If there's anything else, please let me know.
